### ISSUE TITLE
Debug info

### ISSUE THREAD

**Issue by m0n5t3r** [ahmadnassri/action-workflow-run-wait#1]
Can we get some debug parameter? I'm getting "all workflows completed successfully" after the first one finishes, so I guess I'm doing something wrong, but I can't figure out what's the list of workflows it parses, what it's getting from the API, etc.

**Comment by ahmadnassri** [comment]
sure, good idea

**Comment by ahmadnassri** [comment]
added plenty of debgging and also an early exit if no runs are found of the workflow's dependenciesb (which I think is your issue)

**Comment by m0n5t3r** [comment]
thanks; looks like the log gets truncated at ~1000 lines, though, I'll see if I can fork this so I can poke around without bothering you
