### ISSUE TITLE
Workflow not fired

### ISSUE THREAD

**Issue by glensc** [ahmadnassri/action-workflow-run-wait#6]
Trying to understand how this works, but can't figure out why the second workflow is never fired:

- https://github.com/glensc/eventum/runs/2261606770?check_suite_focus=true
- https://github.com/glensc/eventum/tree/82767e6d454ea1a10dd598005deed1085cdeb740/.github/workflows

**Comment by ahmadnassri** [comment]
sorry, I don't see this action used in any of your workflows ... perhaps you should look up the github actions docs for workflows https://docs.github.com/en/actions/managing-workflow-runs

**Comment by glensc** [comment]
@ahmadnassri it uses the same structure your action is supposed to use. job bodies are empty for simplicity.

from the same branch:
- ci job: https://github.com/glensc/eventum/blob/82767e6d454ea1a10dd598005deed1085cdeb740/.github/workflows/ci.yml
- release ob: https://github.com/glensc/eventum/blob/82767e6d454ea1a10dd598005deed1085cdeb740/.github/workflows/release.yml

why is the release job never fired?
